CREATE TABLE IF NOT EXISTS "LiveCoachConversations" (
	"conversationId" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "LiveCoachConversations_conversationId_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"date" varchar(50) NOT NULL,
	"intent" varchar(50) NOT NULL,
	"fulfilled" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "LiftingExercises" (
	"id" serial PRIMARY KEY NOT NULL,
	"userId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"primaryTarget" varchar(100) NOT NULL,
	"detailedTargets" varchar(100)[] NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "FitnessTracks" (
	"id" serial PRIMARY KEY NOT NULL,
	"userId" integer NOT NULL,
	"name" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "SubscriptionPlans" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "SubscriptionPlans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(20) DEFAULT 'free' NOT NULL,
	"dailyConversationLimit" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "Users" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "Users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"authId" varchar(255) NOT NULL,
	"firstName" varchar(50) NOT NULL,
	"lastName" varchar(50),
	"email" varchar(100) NOT NULL,
	"subscriptionPlan" integer DEFAULT 1,
	CONSTRAINT "Users_authId_unique" UNIQUE("authId"),
	CONSTRAINT "Users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "WorkoutsToLiftingExercises" (
	"workoutId" integer NOT NULL,
	"exerciseId" integer NOT NULL,
	"userId" integer NOT NULL,
	"totalSets" integer NOT NULL,
	"totalReps" integer NOT NULL,
	"maxWeight" varchar(10) NOT NULL,
	"serializedSetData" varchar(255)[] DEFAULT '{}' NOT NULL,
	CONSTRAINT "WorkoutsToLiftingExercises_workoutId_exerciseId_pk" PRIMARY KEY("workoutId","exerciseId")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "WorkoutsLifting" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "WorkoutsLifting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"date" varchar(12) NOT NULL,
	"timeStarted" varchar(30) NOT NULL,
	"timeCompleted" varchar(30) NOT NULL,
	"duration" varchar(5) NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "LiveCoachConversations" ADD CONSTRAINT "LiveCoachConversations_userId_Users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."Users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "LiftingExercises" ADD CONSTRAINT "LiftingExercises_userId_Users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."Users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "FitnessTracks" ADD CONSTRAINT "FitnessTracks_userId_Users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."Users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "Users" ADD CONSTRAINT "Users_subscriptionPlan_SubscriptionPlans_id_fk" FOREIGN KEY ("subscriptionPlan") REFERENCES "public"."SubscriptionPlans"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "WorkoutsToLiftingExercises" ADD CONSTRAINT "WorkoutsToLiftingExercises_workoutId_WorkoutsLifting_id_fk" FOREIGN KEY ("workoutId") REFERENCES "public"."WorkoutsLifting"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "WorkoutsToLiftingExercises" ADD CONSTRAINT "WorkoutsToLiftingExercises_exerciseId_LiftingExercises_id_fk" FOREIGN KEY ("exerciseId") REFERENCES "public"."LiftingExercises"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "WorkoutsToLiftingExercises" ADD CONSTRAINT "WorkoutsToLiftingExercises_userId_Users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."Users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "WorkoutsLifting" ADD CONSTRAINT "WorkoutsLifting_userId_Users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."Users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
